; Listing generated by Microsoft (R) Optimizing Compiler Version 19.24.28315.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\su003th\AppData\Local\Temp\1\.NETFramework,Version=v4.5.2.AssemblyAttributes.cpp"
